#!/usr/bin/env python3
"""SIXTY-SECOND net-new-geometry axis for ALL FOUR SLOTS — the DATUM family: one oblique rib
lattice, laid across the whole suit from an origin that is not on the armour at all but on the
WEARER — the crown of the skull. The cuirass, the chausses, the sabatons and the helm are four
windows onto ONE ornament, so a rib that leaves the bottom of the breastplate arrives at the top of
the thigh, and the same rib arrives at the boot.

    the ornament is  CREST  (the lit top of a rib)
                   + SHADE  (the rib's own cast shadow, immediately below it)
                   + FIELD  (the plate between ribs)
    and its position is  u = A(x - x_datum) + B(y - y_datum)  mod P,  read off the WEARER.

*** THIS IS THE FIRST AXIS WHOSE ORIGIN IS OUTSIDE THE PIECE. ***
Every one of the sixty-one before it is anchored to the component it is drawn on. The 11th flutes
from the plate's own edge, the 46th tiles from the plate's own bounding box, the 47th measures
distance to the plate's own silhouette, the 53rd sizes its beads from the room the plate leaves,
the 57th hangs its swags from the plate's own top, the 60th windows its word at the plate's own
leading edge, and the 61st derives every length it has from the plate's own extent. That is why
every one of them is a property of a SHEET: you can hold one sheet up on its own and the ornament
is complete, and it is also why the seam between two pieces of a suit is, on every one of them, a
discontinuity — two ornaments that happen to be made of the same stuff, meeting.

This one has no sheet-level existence at all. Ask it where a rib goes on a boot and it cannot
answer from the boot. It goes where the wearer's head is. Four sheets that know nothing about each
other come out registered because all four asked the same question of the same body, and the
evidence is a thing no previous axis could even be asked for: DRESS THE CHARACTER AND THE RIBS LINE
UP ACROSS THE SEAMS.

*** THE DATUM, AND WHY IT IS THE SKULL. ***
The origin is the CROWN of the wearer's skull, taken per frame from the skin sheet: the topmost run
of 5 or 6 pixels with nothing above it that widens by one pixel each side on each of the next two
rows — the 5 -> 7 -> 9 skull profile that SPRITE_SPEC already fixes. It is the one landmark on the
body that is a landmark in every pose, it belongs to the wearer rather than to any garment, and it
moves with the animation, which is the whole reason the ribs do not crawl. See THE RENDER-PAID
LESSONS below for why it is emphatically NOT the topmost pixel of the wearer.

*** ACCEPTANCE — A NEW KIND: A REGISTRATION. A CLAIM ABOUT A SHARED FRAME OF REFERENCE. ***
Predecessors are accepted on a statistic (46/48/50/52/53), a topology (54), the algebra of an order
(55), a conservation law on a traversal (56), a physical law (57), a group action (58), a census of
a group (59), the complexity of a formal language (60) and a similarity (61). The 61st is the only
one that needed more than one picture, and what it needed was a RANGE of sizes. This one needs
something stronger and different in kind: several pictures that are not of the same thing, that
were generated by separate runs which never saw one another, and that must nonetheless agree about
where the world is. The test is therefore not run on a component and not run on a sheet. It is run
on a SUIT.

    (1) ON-LATTICE     every painted pixel of every sheet carries the role that
                       u = A(x-xd) + B(y-yd) mod P gives it, with (xd,yd) the wearer's crown for
                       that frame. The umbrella; per component.
    (2) SEAMLESS       the phase estimated INDEPENDENTLY off each of the four slot sheets of a suit
                       — chest, legs, boots, helm — is the same phase, in every frame. Four sheets
                       generated in four separate passes agree to the pixel.
    (3) EXTERNAL       the negative clause, and the one that says this axis is not any of the other
                       sixty-one: the phase is NOT recoverable from the piece. For each component
                       the phase a self-anchored axis would give it is computed, and the two agree
                       on no more of the batch than chance (1 in P) allows.
    (4) BODY-TRACKING  in BODY coordinates the phase residual is zero in all 35 active frames,
                       while in SHEET coordinates the phase takes several distinct values. The
                       lattice is nailed to the wearer, not to the canvas; this is the clause that
                       is the difference between an ornament that rides the walk cycle and one
                       that crawls underneath it.
    (5) ONE LATTICE    over all 24 sheets, every frame and every component, exactly ONE (A,B,P) —
                       and it is OBLIQUE, i.e. neither A nor B is zero, so no rib is a row or a
                       column of the sprite grid.

*** THE FIVE CONTROLS, AND THE FIRST OF THEM IS THE ENTIRE POINT. ***
    SELF-ANCHORED   every component takes its own bounding box as origin — which is not a straw
                    man, it is WHAT ALL SIXTY-ONE PRIOR AXES DO. Passes ON-LATTICE on every sheet
                    taken alone; a single sheet of it is INDISTINGUISHABLE from this axis by eye
                    and by any test that looks at one sheet. It fails SEAMLESS and it fails
                    EXTERNAL. You cannot tell the control from the axis until you dress the
                    character, and that is the sharpest statement of what the axis is for.
    FRAME-ANCHORED  origin at the sprite frame's own (0,0): the sheets do register with each other,
                    so it PASSES SEAMLESS, and it fails BODY-TRACKING. Its visible defect is the
                    classic one — the ribs stand still while the character walks through them.
                    It is the honest reason the datum is a body landmark and not the canvas corner,
                    and it is the reason clause 4 exists at all.
    PER-SLOT-PITCH  each slot picks the pitch that best fits its own geometry, i.e. the adaptive
                    boundary rule that NINE earlier axes carry as their hard-won lesson and that
                    the 61st makes compulsory. Here it is fatal: it fails ONE LATTICE, because two
                    pitches cannot cross a seam. The 61st and this one make opposite demands and
                    both are right about their own claim.
    HORIZONTAL      A = 0: level bands, still perfectly registered to the datum. Passes 1-4 and
                    fails the OBLIQUE half of clause 5 — a horizontal band registered to the body
                    is the 12th axis's BANDED LAMELLAR with extra steps, because a level line
                    crossing a seam is not evidence of anything: it would line up by accident.
                    THIS CONTROL IS WHY THE RIBS ARE OBLIQUE. Only a slanted line crossing a seam
                    can only line up on purpose.
    RANDOM-PHASE    a phase drawn per piece. Fails 1-4. The upper collapse boundary: registration
                    without a rule is the 46th CRAQUELURE with a slant.

*** THE PRICE, AND IT IS THE EXACT REVERSE OF THE 61st, AGAIN DELIBERATELY. ***
The 61st CANON fits the ornament to the piece so completely that it has no size of its own; this
one refuses to look at the piece at all. So the piece has NO SAY: a sabaton may catch a crest, or
catch only shade, or in the shortest poses catch neither, and nothing is done about it, because
doing something about it is exactly the SELF-ANCHORED control. A second cost, and it is the first
time in sixty-two axes that the deliverable itself changes: THE ORNAMENT CANNOT BE JUDGED ON A
SINGLE SHEET. A chest of this axis, alone, looks like slanted ribs placed nowhere in particular —
which is precisely what it is, alone. Hence the preview panels for this axis are composites of a
DRESSED character, and `_ZOOM_datum_suit.png` is the axis's real evidence.

*** DISTINCTNESS. ***
  * 11th FLUTING / 43rd GADROON / 42nd STRIGIL — parallel ribs, but vertical, at a pitch measured
    from the piece. Rotate them and anchor them to the piece and you have the SELF-ANCHORED
    control; that is the family this axis is defined against.
  * 12th BANDED LAMELLAR / 55th STRATA — level bands. That is the HORIZONTAL control.
  * 16th TWILL / 25th ARGYLE / 44th ZIGZAG — oblique, but as a repeating cell tiled from the
    piece's own box, and reversing direction. One family of straight parallel ribs that never turns
    is the plainest linear ornament in the set, and it is plain ON PURPOSE: a registration can only
    be seen if the thing being registered is simple enough that the eye can follow one rib across a
    seam. An ornate motif would hide the only claim this axis makes.
  * 61st CANON — the exact complement. Everything from the piece's own extent vs nothing from it.
  * 57th FESTOON — "the first axis that has an UP", i.e. the first to consult the world for a
    DIRECTION. This one consults the world for an ORIGIN, which is strictly more: a direction is
    shared by every piece for free, a position is not.

Geometry:
    lattice   u(x,y) = A*(x - xd) + B*(y - yd)  with (A,B) = (-1, 2), P = 10
              the normal leans LEFT because the character faces left (CONTEXT: 3/4 perspective).
              pitch = P / sqrt(A^2+B^2) = 10/sqrt5 = 4.47 px between rib crests.
    profile   u mod P -> CREST CREST SHADE SHADE FIELD FIELD FIELD FIELD FIELD FIELD
              crest over its own shadow, immediately, with no field row between: at this pitch a
              gap between the lit row and the dark one reads as two thin lines instead of one
              rib with a top. Chosen by rendering five profiles at three pitches through
              finish_array (`--profiles`), not by argument.
    datum     the wearer's skull crown, per gender and per frame, from the skin sheet.

*** NO COMPONENT LABELLING ANYWHERE IN THE GENERATOR, AND THAT IS A PROPERTY, NOT AN OMISSION. ***
Every prior axis begins by segmenting the sheet, because every prior ornament has to know what
piece it is on. This one paints from a global field: a pixel is told its role by its own coordinates
and the wearer's crown, and it does not need to know which garment it belongs to, or whether the
garment has one part or five. `label4` appears in this file only inside the acceptance test and the
diagnostics.

Authoring philosophy identical to gen_canon_axis61.py / gen_cadence_axis60.py: every pattern pixel
is painted ONLY onto pixels ALREADY opaque in the body. Nothing added, nothing removed, silhouette
untouched — QA-safe by construction. Sleep frames (fi >= 60) get a plain recolor.

FINISHING PASS: this generator does NOT shade for itself. Every sheet goes through
`sprite_finish.finish_array(arr, dst)` and is written with `save_finished()`. See CONTEXT.md
"MANDATORY - the finishing pass". Eighteenth generator to call it in-line, after axes 45-61.

Run from repo root:
  python3 scripts/gen_datum_axis62.py
  python3 scripts/gen_datum_axis62.py --lattice    # the lattice, the profile, the datum table
  python3 scripts/gen_datum_axis62.py --cells      # ASCII of real components + the clauses
  python3 scripts/gen_datum_axis62.py --accept     # the clauses over all 24 sheets and every frame
  python3 scripts/gen_datum_axis62.py --profiles   # the profile/pitch A-B that chose the rib
  python3 scripts/gen_datum_axis62.py --sweep      # dressed suits: the axis and the five controls
Then QA (examples):
  python3 scripts/sprite_qa.py _datum_legendary_preview/shirt_warrior_legendary62.png
  python3 scripts/sprite_qa.py _datumdome_helmet_preview/helmet_mage_legendary62.png --y-min 2
  python3 scripts/sprite_qa.py _datum_boots_preview/boots_warrior_legendary_datum.png --y-max 63
"""
import os
import sys
import numpy as np
from PIL import Image

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from gen_mage_ranger_tiers import load, CHAR                 # noqa: E402
from sprite_finish import finish_array, save_finished        # noqa: E402

FW, FH, COLS, NFR = 80, 64, 10, 70
ACTIVE = 60                      # frames >= 60 are the sleep row: plain recolor, no lattice
Q_LO, Q_HI = 0.85, 1.18

# --- THE LATTICE ------------------------------------------------------------------------------
# (A, B) is the normal of the rib family. It leans LEFT because the character faces left. B = 2A
# in magnitude gives a rib that drops one pixel every two columns, which is the shallowest slant
# that is unambiguously not a row of the sprite grid and still legible at 13px.
A, B = -1, 2
P = 10                           # period, in lattice units; pitch = P / sqrt(5) = 4.47 px

R_CREST, R_SHADE, R_FIELD = 0, 1, 2
ROLENAME = {R_CREST: 'CREST', R_SHADE: 'SHADE', R_FIELD: 'FIELD'}
# crest immediately over its own shadow — see --profiles
PROFILE = (R_CREST, R_CREST, R_SHADE, R_SHADE,
           R_FIELD, R_FIELD, R_FIELD, R_FIELD, R_FIELD, R_FIELD)
assert len(PROFILE) == P

# The skull, from SPRITE_SPEC: the crown is a run of 5 (male) or 6 (female, in the cheer pose)
# that widens by one pixel each side on each of the next two rows. Written as the profile it is
# rather than as a width, because a width is exactly what the cheer row makes untrustworthy.
CROWN_W = (5, 6)
SKIN = {'m': 'skin_m1.png', 'f': 'skin_f1.png'}      # silhouette is identical across skin tones

# --- palette ----------------------------------------------------------------------------------
# THREE stops: crest, shade, field. One ramp per class, no second colour family — the eye must
# read the rib off its relief, because the relief is the only thing that crosses the seam.
# Against the neighbours: the 60th took brass / moonstone / verdigris and the 61st oxidised crimson
# / amethyst / deep teal, so this one takes cool pewter, cobalt and moss.
# NO STOP NEAR BLACK — the finishing pass carves the visor as black eye and mouth pixels and a
# near-black darkest stop swallows them (the 49th's lesson). Darkest channel-sums 270 / 244 / 210.
# The crests are chosen for what they BECOME after finish_array lifts the sheet, not for what they
# look like in the swatch (the 61st's salmon lesson).
DATUMPAL = {
    'warrior': ((234, 236, 240), (80, 88, 102), (142, 150, 164)),
    'mage':    ((218, 228, 250), (52, 66, 126), (98, 122, 198)),
    'ranger':  ((224, 238, 198), (62, 92, 56), (118, 158, 90)),
}
BODY = {                          # plain recolor: (dark, mid, light) for the sleep row
    'warrior': ((80, 88, 102), (142, 150, 164), (234, 236, 240)),
    'mage':    ((52, 66, 126), (98, 122, 198), (218, 228, 250)),
    'ranger':  ((62, 92, 56), (118, 158, 90), (224, 238, 198)),
}

SLOTS = {
    'chest': dict(
        outdir='_datum_legendary_preview',
        srcs={'warrior': 'armor_chest_4', 'mage': 'shirt_mage4', 'ranger': 'shirt_ranger4'},
        dst='shirt_%s_legendary62'),
    'legs': dict(
        outdir='_datum_legs_preview',
        srcs={'warrior': 'armor_pants_4', 'mage': 'pants_mage4', 'ranger': 'pants_ranger4'},
        dst='pants_%s_legendary62'),
    'boots': dict(
        outdir='_datum_boots_preview',
        srcs={'warrior': 'armor_boots_4', 'mage': 'boots_mage4', 'ranger': 'boots_ranger4'},
        dst='boots_%s_legendary_datum'),
    'helmet': dict(
        outdir='_datumdome_helmet_preview',
        srcs={'warrior': 'helmet_rare1', 'mage': 'helmet_mage4', 'ranger': 'helmet_ranger4'},
        dst='helmet_%s_legendary62'),
}


# --- the datum --------------------------------------------------------------------------------
def _runs(row):
    out, s = [], None
    for i, v in enumerate(row):
        if v and s is None:
            s = i
        elif not v and s is not None:
            out.append((s, i - 1))
            s = None
    if s is not None:
        out.append((s, len(row) - 1))
    return out


def crown_of(mask):
    """The wearer's skull crown in one frame: (y, x), x rounded to the pixel grid.

    NOT the topmost pixel of the silhouette. In the cheer frames both hands are raised ABOVE the
    head, so the top row of the wearer is a pair of fists — see THE RENDER-PAID LESSONS. What is
    looked for instead is the skull's own shape: a short run with nothing above it that widens by
    one pixel each side on each of the next two rows.
    """
    ys, _ = np.nonzero(mask)
    if len(ys) == 0:
        return None
    for y in range(int(ys.min()), min(mask.shape[0] - 2, 44)):
        for a, b in _runs(mask[y]):
            if not (CROWN_W[0] <= b - a + 1 <= CROWN_W[1]):
                continue
            if y > 0 and mask[y - 1, a:b + 1].any():
                continue
            if not mask[y + 1, max(a - 1, 0):b + 2].all():
                continue
            if not mask[y + 2, max(a - 2, 0):b + 3].all():
                continue
            # x is rounded to the grid: a crown of even width sits on a half pixel, and a
            # half-pixel origin would put every lattice unit on a half pixel too. The rounding
            # is a half-pixel shift of the whole ornament on those four frames and nothing else.
            return y, int(round((a + b) / 2.0))
    return None


_DATUM_CACHE = {}


def datum_table(gender):
    """(y, x) of the wearer's crown for every active frame. THE origin of this axis."""
    if gender in _DATUM_CACHE:
        return _DATUM_CACHE[gender]
    sheet = load(SKIN[gender])
    out = {}
    for fi in range(ACTIVE):
        r, c = fi // COLS, fi % COLS
        m = sheet[r * FH:(r + 1) * FH, c * FW:(c + 1) * FW, 3] > 0
        if not m.any():
            continue
        cr = crown_of(m)
        if cr is not None:
            out[fi] = cr
    _DATUM_CACHE[gender] = out
    return out


def phase_of(datum):
    """The lattice phase a datum implies: u_sheet(x,y) - u(x,y) is constant and equal to this."""
    yd, xd = datum
    return (A * xd + B * yd) % P


# --- painting ---------------------------------------------------------------------------------
def u_sheet(ys, xs):
    """The lattice coordinate in SHEET units — no datum in it. The datum is one subtraction away,
    which is the whole of the difference between this axis and the FRAME-ANCHORED control."""
    return A * xs.astype(np.int64) + B * ys.astype(np.int64)


def paint(fr, mask, stops, phase):
    """Paint the lattice onto every opaque pixel of `mask`. No component labelling: a pixel is
    told its role by its coordinates and the wearer's crown, and needs to know nothing else."""
    ys, xs = np.nonzero(mask)
    if len(ys) == 0:
        return 0
    u = (u_sheet(ys, xs) - phase) % P
    for i in range(len(ys)):
        fr[ys[i], xs[i], :3] = stops[PROFILE[int(u[i])]]
        fr[ys[i], xs[i], 3] = 255
    return len(ys)


def put(fr, y, x, rgb):
    if 0 <= y < FH and 0 <= x < FW:
        fr[y, x, :3] = rgb
        fr[y, x, 3] = 255


def recolor(src, fr, a, D, M, L):
    v = src[..., :3].astype(np.float32).max(-1) / 255.0
    vref = float(np.median(v[a]))
    ratio = v / max(vref, 1e-3)
    for y, x in np.argwhere(a):
        q = ratio[y, x]
        put(fr, y, x, D if q < Q_LO else (L if q > Q_HI else M))


# --- the controls -----------------------------------------------------------------------------
CONTROLS = ('self-anchored', 'frame-anchored', 'per-slot-pitch', 'horizontal', 'random-phase')


def control_phase(mode, fi, gender, mask, slot, rng=None):
    """The phase each control would use for this component/frame. Returns (phase, A, B, P)."""
    if mode == 'self-anchored':                 # what all sixty-one prior axes do
        ys, xs = np.nonzero(mask)
        yd = int(ys.min())
        xd = int(round((int(xs.min()) + int(xs.max())) / 2.0))
        return (A * xd + B * yd) % P, A, B, P
    if mode == 'frame-anchored':                # the canvas corner; registers, but crawls
        return 0, A, B, P
    if mode == 'per-slot-pitch':                # the adaptive-boundary rule, fatal here
        p = {'chest': 10, 'legs': 8, 'boots': 6, 'helmet': 12}[slot]
        d = datum_table(gender).get(fi)
        return ((A * d[1] + B * d[0]) % p if d else 0), A, B, p
    if mode == 'horizontal':                    # registered, but a level line proves nothing
        d = datum_table(gender).get(fi)
        return ((0 * d[1] + B * d[0]) % P if d else 0), 0, B, P
    if mode == 'random-phase':
        return int(rng.integers(0, P)), A, B, P
    raise ValueError(mode)


def paint_mode(fr, mask, stops, fi, gender, slot, mode, rng=None):
    if mode is None:
        d = datum_table(gender).get(fi)
        if d is None:
            return 0
        return paint(fr, mask, stops, phase_of(d))
    if mode == 'self-anchored':
        # per COMPONENT, because that is exactly what the sixty-one prior axes do: each piece is
        # its own world. Painting the whole frame from the union bounding box would be a weaker
        # control and it scored 0.577 on EXTERNAL instead of the 1.000 it must score.
        lbl, n = label4(mask)
        tot = 0
        for k in range(1, n + 1):
            m = lbl == k
            if m.sum() < 4:
                continue
            tot += paint(fr, m, stops, self_phase(m))
        return tot
    ph, a, b, p = control_phase(mode, fi, gender, mask, slot, rng)
    ys, xs = np.nonzero(mask)
    if len(ys) == 0:
        return 0
    u = (a * xs.astype(np.int64) + b * ys.astype(np.int64) - ph) % p
    prof = [PROFILE[int(round(k * P / float(p)))] for k in range(p)]
    for i in range(len(ys)):
        fr[ys[i], xs[i], :3] = stops[prof[int(u[i])]]
        fr[ys[i], xs[i], 3] = 255
    return len(ys)


# --- sheet machinery --------------------------------------------------------------------------
def label4(mask):
    """Self-contained 4-connectivity labelling (scipy-free). Used ONLY by the acceptance test and
    the diagnostics — the generator itself never segments anything."""
    h, w = mask.shape
    labels = np.zeros((h, w), dtype=np.int32)
    n = 0
    stack = []
    for sy in range(h):
        for sx in range(w):
            if mask[sy, sx] and labels[sy, sx] == 0:
                n += 1
                labels[sy, sx] = n
                stack.append((sy, sx))
                while stack:
                    y, x = stack.pop()
                    for ny, nx in ((y - 1, x), (y + 1, x), (y, x - 1), (y, x + 1)):
                        if 0 <= ny < h and 0 <= nx < w and mask[ny, nx] and labels[ny, nx] == 0:
                            labels[ny, nx] = n
                            stack.append((ny, nx))
    return labels, n


def load_any(fname):
    if os.path.exists(os.path.join(CHAR, fname)):
        return load(fname)
    if fname.endswith('_f.png'):
        return load(fname[:-6] + '.png')
    raise FileNotFoundError(fname)


def build(base, cls, gender, slot, mode=None, seed=0):
    D, M, L = BODY[cls]
    stops = DATUMPAL[cls]
    # the RANDOM-PHASE control must draw INDEPENDENTLY per slot. Seeded from the slot as well as
    # from `seed` because a generator that draws the same sequence in every slot is not a random
    # control at all — it is a synchronised one, and it passed SEAMLESS the first time it was run.
    rng = np.random.default_rng(seed * 10 + list(SLOTS).index(slot))
    out = np.zeros_like(base)
    for fi in range(NFR):
        r, c = fi // COLS, fi % COLS
        sl = (slice(r * FH, (r + 1) * FH), slice(c * FW, (c + 1) * FW))
        src = base[sl]
        a = src[..., 3] > 0
        if not a.any():
            continue
        fr = out[sl]
        recolor(src, fr, a, D, M, L)
        if fi >= ACTIVE:
            continue
        paint_mode(fr, a, stops, fi, gender, slot, mode, rng)
    return out


# ---------------------------------------------------------------------------------------------
# THE ACCEPTANCE TEST — a REGISTRATION.
#
# The phase is ESTIMATED off the painted pixels of a sheet, with no reference to the datum that
# produced them: for each of the P possible phases, count how many pixels carry the role that
# phase would give them, and take the argmax. That estimate is then compared with the datum's.
# Estimating rather than assuming is what makes clause 2 a real statement — the four slot sheets
# are asked independently what world they think they are in.
# ---------------------------------------------------------------------------------------------
# Clause 3's threshold. Chance is 1/P = 0.100 and the SELF-ANCHORED control is 1.000 BY
# CONSTRUCTION, so the discriminating value is anywhere between; it is set midway rather than
# tight to the observed 0.156, because a threshold tuned to the observation is not a test.
EXT_MAX = 0.50


def read_roles(fr, mask, stops):
    ys, xs = np.nonzero(mask)
    px = fr[ys, xs, :3].astype(np.int32)
    pal = np.array(stops, dtype=np.int32)
    return ys, xs, ((px[:, None, :] - pal[None, :, :]) ** 2).sum(-1).argmin(1)


def estimate_phase(fr, mask, stops, lat=None):
    """(best phase, agreement fraction) read off the pixels alone.

    `lat` is the (a, b, p, profile) the reader assumes. It is a parameter and not the module
    constant because the CONTROLS must be read on their own lattice: a control read through this
    axis's lattice would fail everything for the uninteresting reason that the reader cannot see
    it, and the whole value of a control is that it fails for its OWN reason.
    """
    a, b, p, prof = lat if lat else (A, B, P, PROFILE)
    ys, xs, role = read_roles(fr, mask, stops)
    if len(ys) == 0:
        return None, 0.0
    u0 = a * xs.astype(np.int64) + b * ys.astype(np.int64)
    prof = np.array(prof)
    best, bestn = 0, -1
    for ph in range(p):
        want = prof[(u0 - ph) % p]
        n = int((want == role).sum())
        if n > bestn:
            best, bestn = ph, n
    return best, bestn / float(len(ys))


def self_phase(mask, lat=None):
    """The phase this component would have chosen for itself — i.e. what all sixty-one prior axes
    would do: origin at the piece's own top edge and horizontal centre."""
    a, b, p = (lat[0], lat[1], lat[2]) if lat else (A, B, P)
    ys, xs = np.nonzero(mask)
    yd = int(ys.min())
    xd = int(round((int(xs.min()) + int(xs.max())) / 2.0))
    return (a * xd + b * yd) % p


def accept_all(verbose=True):
    """The five clauses over all 24 sheets, every active frame, every component."""
    nsheet = ncomp = nbad = 0
    seam_ok = seam_tot = 0
    ext_hit = ext_tot = 0
    body_res = set()
    sheet_phases = set()
    lattices = set()
    per_frame_phase = {}                     # (cls, gender, fi) -> {slot: phase}
    firsts = []

    for slot, cfg in SLOTS.items():
        for cls, stem in cfg['srcs'].items():
            for gender, suffix in (('m', ''), ('f', '_f')):
                base = load_any('%s%s.png' % (stem, suffix))
                arr = build(base, cls, gender, slot)
                nsheet += 1
                stops = DATUMPAL[cls]
                dt = datum_table(gender)
                for fi in range(ACTIVE):
                    r, c = fi // COLS, fi % COLS
                    sl = (slice(r * FH, (r + 1) * FH), slice(c * FW, (c + 1) * FW))
                    a = base[sl][..., 3] > 0
                    if not a.any() or fi not in dt:
                        continue
                    fr = arr[sl]
                    want = phase_of(dt[fi])
                    lattices.add((A, B, P))

                    # (1) ON-LATTICE, per component
                    lbl, n = label4(a)
                    for k in range(1, n + 1):
                        m = lbl == k
                        if m.sum() < 4:
                            continue
                        ncomp += 1
                        ys, xs, role = read_roles(fr, m, stops)
                        prof = np.array(PROFILE)
                        got = prof[(u_sheet(ys, xs) - want) % P]
                        bad = int((got != role).sum())
                        if bad:
                            nbad += 1
                            if len(firsts) < 10:
                                firsts.append('ON-LATTICE %s %s%s f%d comp%d: %d/%d px off'
                                              % (slot, cls, suffix, fi, k, bad, len(ys)))
                        # (3) EXTERNAL — would the piece's own origin have produced this?
                        ext_tot += 1
                        if self_phase(m) == want:
                            ext_hit += 1

                    # (2) SEAMLESS — phase estimated off THIS sheet alone
                    est, agree = estimate_phase(fr, a, stops)
                    per_frame_phase.setdefault((cls, gender, fi), {})[slot] = est
                    seam_tot += 1
                    if est == want and agree > 0.999:
                        seam_ok += 1
                    elif len(firsts) < 10:
                        firsts.append('SEAMLESS %s %s%s f%d: estimated %s, datum says %s (%.3f)'
                                      % (slot, cls, suffix, fi, est, want, agree))

                    # (4) BODY-TRACKING — the residual in body coordinates
                    body_res.add((est - want) % P)
                    sheet_phases.add(est)

    agree_slots = sum(1 for v in per_frame_phase.values() if len(set(v.values())) == 1)
    if verbose:
        print('ACCEPTANCE — a REGISTRATION, over all %d sheets, every active frame:' % nsheet)
        print('  (1) ON-LATTICE     components %d, off-lattice %d -> %s'
              % (ncomp, nbad, 'PASS' if nbad == 0 else 'FAIL'))
        print('  (2) SEAMLESS       sheet-phases matching the datum %d/%d;'
              % (seam_ok, seam_tot))
        print('                     suit-frames where all 4 slots agree %d/%d -> %s'
              % (agree_slots, len(per_frame_phase),
                 'PASS' if agree_slots == len(per_frame_phase) and seam_ok == seam_tot else 'FAIL'))
        print('  (3) EXTERNAL       components whose OWN origin would give the same phase '
              '%d/%d = %.3f  (chance %.3f, must be < %.2f) -> %s'
              % (ext_hit, ext_tot, ext_hit / max(ext_tot, 1), 1.0 / P, EXT_MAX,
                 'PASS' if ext_hit / max(ext_tot, 1) < EXT_MAX else 'FAIL'))
        print('                     it sits above chance, and that is not a defect: a garment\'s')
        print('                     top edge and the wearer\'s crown are both on the same body,')
        print('                     so the two origins are correlated. The claim is only that the')
        print('                     piece does not DETERMINE the phase — the control does, at 1.0.')
        print('  (4) BODY-TRACKING  residual phases in BODY coords %s (must be {0});'
              % sorted(body_res))
        print('                     distinct phases in SHEET coords %d (must be > 1) -> %s'
              % (len(sheet_phases),
                 'PASS' if body_res == {0} and len(sheet_phases) > 1 else 'FAIL'))
        print('  (5) ONE LATTICE    distinct (A,B,P) %s; oblique (A!=0 and B!=0) %s -> %s'
              % (sorted(lattices), A != 0 and B != 0,
                 'PASS' if len(lattices) == 1 and A != 0 and B != 0 else 'FAIL'))
        for f in firsts:
            print('     VIOLATION %s' % f)
    ok = (nbad == 0 and seam_ok == seam_tot
          and agree_slots == len(per_frame_phase)
          and ext_hit / max(ext_tot, 1) < EXT_MAX and body_res == {0} and len(sheet_phases) > 1
          and len(lattices) == 1 and A != 0 and B != 0)
    if verbose:
        print('OVERALL: %s' % ('ALL PASS' if ok else 'FAIL'))
    return ok


def _lattice_of(mode, slot):
    """The lattice a control is READ on. A control read through this axis's lattice would fail
    everything for the uninteresting reason that the reader cannot see it; each is read on its
    own, so that what it fails is its own fault and not the reader's."""
    if mode == 'per-slot-pitch':
        p = {'chest': 10, 'legs': 8, 'boots': 6, 'helmet': 12}[slot]
        return (A, B, p, tuple(PROFILE[int(round(k * P / float(p)))] for k in range(p)))
    if mode == 'horizontal':
        return (0, B, P, PROFILE)
    return (A, B, P, PROFILE)


def _clauses_for(mode, cls='warrior', gender='m'):
    """SEAMLESS / EXTERNAL / BODY-TRACKING / ONE LATTICE for the axis (mode=None) or a control,
    all measured the same way, on one suit."""
    suffix = '_f' if gender == 'f' else ''
    dt = datum_table(gender)
    stops = DATUMPAL[cls]
    phases, body_res, lattices = {}, set(), set()
    ext_hit = ext_tot = 0
    for slot, cfg in SLOTS.items():
        lat = _lattice_of(mode, slot) if mode else (A, B, P, PROFILE)
        lattices.add(lat[:3])
        base = load_any('%s%s.png' % (cfg['srcs'][cls], suffix))
        arr = build(base, cls, gender, slot, mode=mode, seed=7)
        for fi in range(ACTIVE):
            r, c = fi // COLS, fi % COLS
            sl = (slice(r * FH, (r + 1) * FH), slice(c * FW, (c + 1) * FW))
            a = base[sl][..., 3] > 0
            if not a.any() or fi not in dt:
                continue
            fr = arr[sl]
            lbl, n = label4(a)
            for k in range(1, n + 1):
                m = lbl == k
                if m.sum() < 4:
                    continue
                est, _ = estimate_phase(fr, m, stops, lat)
                ext_tot += 1
                # EXTERNAL is asked per component and compares the phase actually on the pixels
                # with the phase the piece's own bounding box would have chosen. Nothing about
                # the mode is hard-coded here: SELF-ANCHORED comes out at 1.000 because it IS
                # that rule, not because it is named in an if-statement.
                if est == self_phase(m, lat):
                    ext_hit += 1
            est, agree = estimate_phase(fr, a, stops, lat)
            phases.setdefault(fi, {})[slot] = est
            # in BODY coordinates: how far the sheet's phase sits from the wearer's crown, in
            # units of the lattice actually in use. Constant across frames = tracks the body.
            body_res.add((est - (lat[0] * dt[fi][1] + lat[1] * dt[fi][0])) % lat[2])
    disagree = sum(1 for v in phases.values()
                   if len(v) != len(SLOTS) or len(set(v.values())) != 1)
    return dict(disagree=disagree, nframes=len(phases),
                ext=ext_hit / max(ext_tot, 1), body=sorted(body_res),
                lattices=sorted(lattices))


def controls_report():
    """The axis and the five controls, every one measured by the same four clauses."""
    print('== THE AXIS AND THE FIVE CONTROLS, warrior suit, all measured the same way')
    print('   %-15s %-10s %-9s %-22s %s'
          % ('', 'SEAMLESS', 'EXTERNAL', 'BODY-TRACKING', 'ONE LATTICE / OBLIQUE'))
    rows = [(None, 'DATUM (axis)')] + [(m, m) for m in CONTROLS]
    out = {}
    for mode, label in rows:
        r = _clauses_for(mode)
        seam = 'PASS' if r['disagree'] == 0 else 'FAIL %d/%d' % (r['disagree'], r['nframes'])
        ext = ('PASS %.3f' % r['ext']) if r['ext'] < EXT_MAX else ('FAIL %.3f' % r['ext'])
        bod = ('PASS (residual %s)' % r['body']) if len(r['body']) == 1 \
            else ('FAIL (%d residuals)' % len(r['body']))
        lats = r['lattices']
        obl = all(a != 0 and b != 0 for a, b, _ in lats)
        one = ('PASS' if len(lats) == 1 and obl
               else ('FAIL not oblique' if len(lats) == 1 else 'FAIL %d pitches' % len(lats)))
        print('   %-15s %-10s %-9s %-22s %s' % (label, seam, ext, bod, one))
        out[label] = r
    print('   SELF-ANCHORED is the row to read: it is what every prior axis does, it is')
    print('   indistinguishable from this axis on any single sheet, and it disagrees with itself')
    print('   across the four slots in every frame of the suit.')
    print('   HORIZONTAL fails BODY-TRACKING as well as OBLIQUE, and the reason is worth keeping:')
    print('   with A = 0 the lattice coordinate is 2y, so it only ever takes EVEN residues and')
    print('   samples five of its own ten profile positions. Its phase is therefore identifiable')
    print('   only up to +/-1 and the reader picks the lower of the pair, which shows up as two')
    print('   residuals. A level lattice on an integer grid is degenerate — one more argument for')
    print('   OBLIQUE than the one the clause was written for.')
    return True


# --- diagnostics ------------------------------------------------------------------------------
def lattice_report():
    import math
    print('== THE LATTICE   u = %d(x - xd) + %d(y - yd)   mod %d' % (A, B, P))
    print('   pitch  %.3f px between crests   slant  1 px down every %.1f px across'
          % (P / math.sqrt(A * A + B * B), abs(B / float(A))))
    print('   profile (u mod P):  ' + ' '.join(ROLENAME[r][0] for r in PROFILE))
    for g in ('m', 'f'):
        dt = datum_table(g)
        print('== THE DATUM  gender %s   %d active frames resolved' % (g, len(dt)))
        seen = {}
        for fi in sorted(dt):
            seen.setdefault(dt[fi], []).append(fi)
        for d in sorted(seen):
            print('   crown (y=%2d, x=%2d)  phase %2d   frames %s'
                  % (d[0], d[1], phase_of(d), ','.join(str(f) for f in seen[d])))


def _big_comp(arr, fi=0):
    r, c = fi // COLS, fi % COLS
    src = arr[r * FH:(r + 1) * FH, c * FW:(c + 1) * FW]
    a = src[..., 3] > 0
    lbl, n = label4(a)
    counts = np.bincount(lbl.ravel())
    counts[0] = 0
    return (lbl == int(counts.argmax())) if n else a


def dump_cells():
    """ASCII of real components under the axis, with the clauses stated on each."""
    legend = {R_CREST: '^', R_SHADE: 'v', R_FIELD: '-'}
    dt = datum_table('m')
    ph = phase_of(dt[0])
    stops = DATUMPAL['warrior']
    allpass = True
    for label, fname in (('warrior chest', 'armor_chest_4.png'),
                         ('warrior legs', 'armor_pants_4.png'),
                         ('warrior boot', 'armor_boots_4.png'),
                         ('warrior helm', 'helmet_rare1.png')):
        comp = _big_comp(load_any(fname))
        fr = np.zeros(comp.shape + (4,), dtype=np.uint8)
        paint(fr, comp, stops, ph)
        ys, xs = np.nonzero(comp)
        y0, y1, x0, x1 = ys.min(), ys.max(), xs.min(), xs.max()
        est, agree = estimate_phase(fr, comp, stops)
        sph = self_phase(comp)
        print('== %s   frame 0, crown at (y=%d, x=%d), datum phase %d'
              % (label, dt[0][0], dt[0][1], ph))
        ys2, xs2, role = read_roles(fr, comp, stops)
        rmap = np.full(comp.shape, -1, np.int8)
        rmap[ys2, xs2] = role
        for y in range(y0, y1 + 1):
            print('   ' + ''.join(legend[int(rmap[y, x])] if comp[y, x] else ' '
                                  for x in range(x0, x1 + 1)))
        ok = (est == ph and agree > 0.999)
        print('   phase read back off the pixels: %d (%.3f agreement) -> %s'
              % (est, agree, 'ON-LATTICE' if ok else 'FAIL'))
        print('   the phase this piece would have chosen for itself: %d  %s'
              % (sph, '(differs — EXTERNAL)' if sph != ph else '(coincides — 1 chance in %d)' % P))
        allpass = allpass and ok
    print()
    print('legend: ^ crest   v shade   - field')
    print('OVERALL: %s' % ('ALL PASS' if allpass else 'FAIL'))
    return allpass


SUIT_SRC = {
    'warrior': dict(chest='armor_chest_4', legs='armor_pants_4',
                    boots='armor_boots_4', helmet='helmet_rare1'),
    'mage': dict(chest='shirt_mage4', legs='pants_mage4',
                 boots='boots_mage4', helmet='helmet_mage4'),
    'ranger': dict(chest='shirt_ranger4', legs='pants_ranger4',
                   boots='boots_ranger4', helmet='helmet_ranger4'),
}


def dress(cls, gender='m', frames=(0,), mode=None, finish=True):
    """Composite a DRESSED character — the only view in which this axis says anything."""
    suffix = '_f' if gender == 'f' else ''
    sheets = {}
    for slot in ('legs', 'boots', 'chest', 'helmet'):
        base = load_any('%s%s.png' % (SUIT_SRC[cls][slot], suffix))
        arr = build(base, cls, gender, slot, mode=mode, seed=7)
        if finish:
            arr, _ = finish_array(arr, '%s/%s%s.png'
                                  % (SLOTS[slot]['outdir'], SLOTS[slot]['dst'] % cls, suffix))
        sheets[slot] = arr
    outs = []
    for fi in frames:
        r, c = fi // COLS, fi % COLS
        comp = np.zeros((FH, FW, 4), np.uint8)
        for slot in ('legs', 'boots', 'chest', 'helmet'):
            cell = sheets[slot][r * FH:(r + 1) * FH, c * FW:(c + 1) * FW]
            m = cell[..., 3] > 0
            comp[m] = cell[m]
        outs.append(comp)
    return outs


def sweep(path='_diag_datum_sweep.png', zoom=12):
    """THE AXIS AND THE FIVE CONTROLS, on a dressed character. SELF-ANCHORED is the cell to stare
    at: on any single sheet it is this axis; here the ribs step at every seam."""
    modes = [None] + list(CONTROLS)
    crop = (slice(14, 63), slice(26, 58))
    h = (crop[0].stop - crop[0].start) * zoom
    w = (crop[1].stop - crop[1].start) * zoom
    pad = 8
    img = Image.new('RGBA', (pad + len(modes) * (w + pad), pad + 3 * (h + pad)), (24, 24, 28, 255))
    for i, cls in enumerate(('warrior', 'mage', 'ranger')):
        for j, m in enumerate(modes):
            c = dress(cls, 'm', (0,), mode=m)[0]
            im = Image.fromarray(c[crop]).resize((w, h), Image.NEAREST)
            img.paste(im, (pad + j * (w + pad), pad + i * (h + pad)))
    img.save(path)
    print('wrote %s   columns: DATUM, %s' % (path, ', '.join(CONTROLS)))


def profiles_diag(path='_diag_datum_profiles.png', zoom=10):
    """The A-B that chose the rib: five profiles at three pitches, on a dressed warrior, through
    the finishing pass. Kept because the choice was made by looking, not by arguing."""
    global P, PROFILE
    C, S, F = R_CREST, R_SHADE, R_FIELD
    cands = [
        ('P8 CCFFSSFF', 8, (C, C, F, F, S, S, F, F)),
        ('P10 CCFSSFFFFF', 10, (C, C, F, S, S, F, F, F, F, F)),
        ('P10 CCSSFFFFFF', 10, (C, C, S, S, F, F, F, F, F, F)),
        ('P12 CCFSSFFFFFFF', 12, (C, C, F, S, S, F, F, F, F, F, F, F)),
        ('P12 CCCFSSSFFFFF', 12, (C, C, C, F, S, S, S, F, F, F, F, F)),
    ]
    crop = (slice(14, 63), slice(26, 58))
    h = (crop[0].stop - crop[0].start) * zoom
    w = (crop[1].stop - crop[1].start) * zoom
    pad = 8
    img = Image.new('RGBA', (pad + len(cands) * (w + pad), pad + 3 * (h + pad)), (24, 24, 28, 255))
    P0, PR0 = P, PROFILE
    for i, cls in enumerate(('warrior', 'mage', 'ranger')):
        for j, (name, p, prof) in enumerate(cands):
            P, PROFILE = p, prof
            c = dress(cls, 'm', (0,))[0]
            im = Image.fromarray(c[crop]).resize((w, h), Image.NEAREST)
            img.paste(im, (pad + j * (w + pad), pad + i * (h + pad)))
    P, PROFILE = P0, PR0
    img.save(path)
    print('wrote %s   columns: %s' % (path, ', '.join(c[0] for c in cands)))


def main():
    if '--lattice' in sys.argv:
        lattice_report()
        return
    if '--cells' in sys.argv:
        dump_cells()
        return
    if '--accept' in sys.argv:
        accept_all()
        print()
        controls_report()
        return
    if '--sweep' in sys.argv:
        sweep()
        return
    if '--profiles' in sys.argv:
        profiles_diag()
        return
    for slot, cfg in SLOTS.items():
        outdir = cfg['outdir']
        os.makedirs(outdir, exist_ok=True)
        for cls, stem in cfg['srcs'].items():
            for gender, suffix in (('m', ''), ('f', '_f')):
                base = load_any('%s%s.png' % (stem, suffix))
                arr = build(base, cls, gender, slot)
                dst = '%s/%s%s.png' % (outdir, cfg['dst'] % cls, suffix)
                # MANDATORY finishing pass — never a bespoke shade() in a generator.
                arr, info = finish_array(arr, dst)
                save_finished(arr, dst)
                print('wrote %-64s opaque_px=%-6d finish=%s/%s'
                      % (dst, (arr[..., 3] > 0).sum(), info['slot'], info['variant']))


if __name__ == '__main__':
    main()
