#!/usr/bin/env python3
"""FIFTY-FIRST net-new-geometry axis for ALL FOUR SLOTS — the FLOWGRAIN family (a continuous
DIRECTOR FIELD with topological defects): the surface is figured with one unbroken family of raised
ridges whose DIRECTION IS A SMOOTH FUNCTION OF POSITION — the grain sweeps across the plate, wraps
around a KNOT where the ridges close on themselves, and splits at a DELTA where two streams of grain
part company. It is the figure in a burl, the water in a pattern-welded blade around a punched eye,
the flow in a fingerprint.

    the ornament is  RIDGE  (a raised convex member, lit crest -> flank -> groove across its width)
                   + FIELD  (the ridge's DIRECTION at a point, which is different at every point)
                   + DEFECT (the two singular points the whole field is organised around:
                             a KNOT/core where ridges close, a DELTA where they bifurcate)

*** THIS IS THE FIRST CONTINUOUS-FIELD AXIS, AND THE FIRST AXIS WITH NO REPEATING MEMBER. ***
Every one of the fifty prior axes is generated by a UNIT. Forty of them stamp a congruent cell on a
lattice (hexagon, scale, arch, coffer, bay); ten run a congruent member along a track (flute, wave,
meander, cable, guilloche, strigil, gadroon, zigzag); the three most recent break the unit's
*content* — 48th cosmati gives it a hierarchy of sizes, 49th dendrite gives it descent, 50th runic
gives it a vocabulary — but all three still lay their content into a ruled, periodic carrier, and in
all fifty you can point at the thing that repeats. Here you cannot. Tone is an ANALYTIC FUNCTION of
position, `t = frac(PHI(x, y) / 2*pi)`, and no two ridges on the plate are congruent: they have
different lengths, different curvatures, different orientations, and some of them close into loops
while others run off the silhouette. The axis is not a pattern that has been placed on the armour,
it is a FIELD that the armour has been cut out of, and the structure that makes it read as ornament
rather than as noise is not a grid — it is the field's SINGULARITIES.

The families it could be confused with, and why each fails:
  * The line axes — 11th fluting, 42nd strigil, 43rd gadroon, 44th zigzag, 22nd wave, 30th cable —
    all have a GLOBAL DIRECTION. A flute is vertical everywhere on the piece; a strigil S-curve is
    the same S at every column; a wave is the same sine translated. Rotate the piece and you can
    still name the one direction the family runs. Here there is no such direction: the grain runs
    -28 deg at the hem, turns through the vertical at the knot, and comes back the other way past
    the delta. Direction is a LOCAL property, which is the whole subject.
  * The 47th mokume is the sharpest near miss, because it is also unruled and its bands also curve.
    But mokume's bands are CONTOURS OF THE SILHOUETTE — tone is f(distance-to-edge), so the figure
    is a property of the OUTLINE and every band is a scaled copy of the boundary, closed and nested.
    Flowgrain's ridges are contours of a field that knows nothing about the outline; they are open,
    they are not nested, they cross the silhouette at every angle, and the piece can be reshaped
    without changing the grain. Nesting is containment; this is flow.
  * The 24th spiral and 28th concentric close their curves around TILED CENTRES — a periodic
    lattice of cores, each core's neighbourhood a copy of the last. This axis has TWO singular
    points on the whole piece, of TWO DIFFERENT KINDS (a +1/2 core and a -1/2 delta), and away from
    them the field is not organised around anything.
  * The 46th craquelure is the other axis with no repeating unit, and the relation is worth stating
    because it is the exact opposite failure of periodicity. Craquelure is DISORDER without
    periodicity: a jittered partition, C-nothing continuous, no straight line anywhere, every
    junction an accident of a PRNG. Flowgrain is SMOOTH ORDER without periodicity: one differentiable
    function, no randomness at all, every ridge exactly parallel to its neighbour everywhere, and
    the only two places anything happens are dictated by topology, not by chance. One is noise, the
    other is a flow; they cannot be mistaken for one another at 1x.

RELIEF, and the second thing that is new here. Every prior axis picks its stop from WHERE a pixel
sits in the cell. This one picks the crest stop from WHICH WAY THE RIDGE IS POINTING: a crest whose
ridge runs across the light (the light is upper-left, as everywhere in the set) takes the bright
nickel stop, a crest whose ridge runs along the light takes the dull one, and because direction
varies continuously the highlight MIGRATES along the grain — the shimmer that makes real figured
material look wet. That is orientation-dependent shading, and it is only possible on an axis whose
subject is orientation.

Geometry. The phase is the classic director field with point defects,

    PHI(x, y) = (2*pi / PITCH) * (x*cos(ALPHA) + y*sin(ALPHA))          the carrier
                + SUM_i  q_i * w(r_i) * atan2(y - dy_i, x - dx_i)      the defects

with charges q = +2 (the KNOT) and q = -2 (the DELTA): walk a circle around one and the phase gains
two whole periods, so two extra ridges are inserted there and every ridge nearby has to bend to make
room. The charges sum to zero, so far from the pair the grain is undisturbed and the piece keeps a
prevailing sweep. Both defects are placed in COMPONENT-LOCAL fractions, with the knot LEFT of centre
and high, per the standing rule that the character faces LEFT.

Two terms there are not cosmetic, and each is tuned against a specific failure:

  * q MUST BE AN INTEGER. atan2 jumps by 2*pi across its branch cut, so the phase jumps by q * 2*pi
    along a ray out of each core, and the banding frac(PHI / 2*pi) only hides that jump when q is a
    whole number of periods. The honest half-charge of a real fingerprint delta (q = 1/2) leaves half
    a period of mismatch along a straight line right across the piece — and a straight discontinuity
    is the one thing a flow must not have. It reads as a scratch, or worse as a plate seam, and the
    armour looks like two pieces butted together.
  * w(r) = r^2 / (r^2 + CORE_R^2) rolls each defect off inside CORE_R. An undamped atan2 has
    unbounded gradient at its centre, so ridge spacing collapses to nothing there and the knot comes
    out as a 3px smear of alternating pixels — the mush the 30th cable was retuned to avoid. Damping
    trades topological purity for a core whose ridges stay a pixel apart: on a 13x20 torso
    |grad PHI| p95/median falls from 2.53 to 1.39, i.e. from "much of the field is compressed" to
    "nowhere is the spacing more than a third tighter than the carrier's". A real ridge core is a
    tight curve rather than a singularity, so this is also the truer picture.

Authoring philosophy identical to gen_runic_axis50.py / gen_dendrite_axis49.py: every pattern pixel
is painted ONLY onto pixels ALREADY opaque in the body, so the generator CANNOT create isolated
pixels, background bleed or extra components — QA-safe by construction. Sleep frames (fi >= 60) get
a plain body recolor.

FINISHING PASS: this generator does NOT shade for itself. Every sheet goes through
`sprite_finish.finish_array(arr, dst)` and is written with `save_finished()` — the canonical chain
(no-smooth shading with protect=False, shirt pauldron/gorget/chest-plate separation, helmet black
eye+mouth visor with NO full-silhouette rim, hat brim/crease folds for open headgear). See
CONTEXT.md "MANDATORY - the finishing pass".

Run from repo root:
  python3 scripts/gen_flowgrain_axis51.py
  python3 scripts/gen_flowgrain_axis51.py --field     # ASCII dump of the field + gradient stats
  python3 scripts/gen_flowgrain_axis51.py --swatch    # bare motif on a test plate, no sheets
  python3 scripts/gen_flowgrain_axis51.py --sweep     # PITCH sweep on a real torso AND a real leg
Then QA (examples):
  python3 scripts/sprite_qa.py _flowgrain_legendary_preview/shirt_warrior_legendary51.png
  python3 scripts/sprite_qa.py _flowgraindome_helmet_preview/helmet_mage_legendary51.png --y-min 2
  python3 scripts/sprite_qa.py _flowgrain_boots_preview/boots_warrior_legendary_flowgrain.png --y-max 63
"""
import os
import sys
import numpy as np
from PIL import Image

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from gen_mage_ranger_tiers import load, CHAR                 # noqa: E402
from sprite_finish import finish_array, save_finished        # noqa: E402

FW, FH, COLS, NFR = 80, 64, 10, 70
MIN_PX = 12
Q_LO, Q_HI = 0.85, 1.18
TAU = 2.0 * np.pi

# --- Flowgrain constants --------------------------------------------------------------------
# PITCH is the ridge period in pixels of the UNDISTURBED carrier (near the defects the field
# stretches and compresses it, which is the point). Swept 5.5/4.5/4.0/3.6/3.0 (--sweep) on a real
# torso AND a real leg. Like the 49th and 50th this axis is bounded on both sides by a collapse into
# an OLDER axis rather than into mush, but here the two ends are DIFFERENT axes:
#   5.5  a 13px torso carries 3 ridges and a thigh 2. Three curved bands on a plate is the 47th
#        MOKUME — at that count the eye reads them as contours of the silhouette, because there are
#        too few of them to establish that they are contours of anything else. The flow dies for
#        want of members and the knot has no room to close.
#   4.5  4 ridges on the torso; the knot closes but only just, and the delta falls off the hip.
#   4.0  5 ridges, both defects legible on the chest, still one clear ridge either side of the knot.
#   3.6  6 ridges on the torso and 4 down a thigh, the knot closing inside 5px, the delta split
#        visible, crest-flank-groove still a clean 3-stop profile across each member — chosen.
#   3.0  the profile loses its flank: crest and groove sit adjacent, so each ridge is a 1px light /
#        1px dark pair and the convex relief is gone. What is left is a fine two-tone hatch whose
#        local direction the eye cannot resolve at 1x, and a hatch that dense reads as the 16th
#        TWILL with a wobble — direction, the entire subject, becomes unreadable exactly when there
#        is most of it on the plate.
PITCH = 3.6
# ALPHA is the direction of the phase GRADIENT, so the undisturbed ridges run perpendicular to it.
# 62 deg puts the prevailing grain at about -28 deg from the horizontal, deliberately off every
# family axis in the set: horizontal grain reads as the 47th mokume or a banded lamellar, vertical
# as the 11th fluting or 43rd gadroon, 45 deg as the 16th twill. The defect pair then swings the
# local direction through roughly +/-90 deg of that, so no one direction owns the plate.
ALPHA = np.deg2rad(62.0)
# Defects as (charge, x, y), the position in fractions of the component bounding box. The KNOT is
# left of centre and high — the character faces LEFT, so the organising feature of the field belongs
# on the lit side. The DELTA sits below and right of it, a TIGHT pair: swept both, and a pair spread
# to opposite corners (0.36,0.32)/(0.68,0.70) rotates the grain through 90 deg over the whole middle
# of the plate, which lands a broad horizontal band across the chest and reads as the 8th SIDE-STRIPE
# with texture in it. Bringing the two cores within about 7px keeps the disturbance local: the knot
# closes, the delta splits, and the rest of the piece keeps its prevailing sweep, which is what makes
# the two singular points read as FEATURES of a flow instead of as a seam between two textures.
#
# THE CHARGE MUST BE AN INTEGER, and that is the one hard constraint in the whole axis. The defect
# term is `q * atan2(...)`, and atan2 jumps by 2*pi across its branch cut, so the phase jumps by
# q * 2*pi along a ray running out from each core. Banding takes `frac(PHI / 2*pi)`, so an INTEGER q
# makes that jump land on a whole number of periods and vanish — the ridges cross the cut without a
# join. A fractional charge (q = 0.5, the honest half-charge of a real fingerprint delta) leaves half
# a period of mismatch along a straight line right across the piece, and a straight discontinuity is
# the one thing a flow must not have: it reads as a scratch, or worse as a plate seam, and the field
# looks like two pieces of armour butted together. Swept 1 / 2 / 3: at 1 the grain barely bends on a
# 13px torso and the axis is a diagonal 11th fluting; at 2 the knot closes inside 5px with a clear
# ridge either side and the delta's split is legible; at 3 the spacing at the cores compresses past
# 1px and both cores turn into a smear.
KNOT = (+2.0, 0.32, 0.30)
DELTA = (-2.0, 0.62, 0.52)
CORE_R = 3.0       # damping radius; below this the defect term is rolled off — see docstring
# Ridge profile across one period. Convex member: a lit crest, a mid flank falling away from it, a
# groove at the bottom of the cut. Boundaries chosen so at PITCH 3.6 each stop lands on about one
# pixel; the crest gets the largest share because it is the only stop that carries direction.
T_CREST, T_FLANK, T_GROOVE = 0.30, 0.58, 0.82
# How square-on to the light a ridge must run before its crest takes the bright stop. The threshold
# is on |ridge normal . light|, and the geometry is not symmetric the way it looks: with the light
# up-left, a ridge at 45 deg PARALLEL to it ('\') is the only orientation that goes fully dull, while
# horizontal, vertical and '/' ridges all sit at 0.71 or above. So a threshold under about 0.8 lights
# most of the plate, the lift stops being a highlight, and on a 13px torso the strip where the field
# turns horizontal comes out as one hard white bar across the chest — a bar reads as a BELT (the 8th
# side-stripe) and swamps the grain under it. At 0.86 only the crests within about 10 deg of square-on
# lift, the shimmer is a minority of the crest, and it MIGRATES as the direction turns, which is the
# whole point of an orientation-shaded axis.
FACE_T = 0.86

# Per class, five stops: crest lit across the light / crest lit along it / flank / groove / deep.
#   * No stop is near pure black. This is a HELMET constraint, not taste: the finishing pass carves
#     the visor as black eye and mouth pixels and a near-black groove swallows the face slit (the
#     lesson the 49th paid for on its first cut).
#   * Every pale stop is clear of the skin ramp. On a narrow female chest the crests are most of
#     what is visible and a warm off-white would read as bare shoulder at 1x (the 47th's rose gold).
#   * The two crest stops are deliberately CLOSE together. The first cut ran them 236 against 170,
#     and because the orientation term switches between them on a threshold, every stretch of grain
#     that happened to face the light came out as a hard white bar — the highlight stopped reading as
#     a highlight and started reading as a second, brighter pattern laid over the first. A migrating
#     highlight has to be a shimmer, not an element.
GRAIN = {
    # pattern-welded steel: cold greys, nickel crests, the water in the billet
    'warrior': ((214, 224, 240), (168, 178, 196), (112, 120, 138), (70, 76, 92), (48, 52, 66)),
    # aether current: deep indigo shot through with luminous ice — the first indigo ground in the
    # set (the 50th's mage ground is violet-black, and the two are only ever seen side by side)
    'mage':    ((196, 232, 252), (140, 178, 224), (84, 110, 176), (52, 66, 124), (34, 42, 86)),
    # figured olive ash: green-grey heartwood with pale sage-gold figure, pushed green off skin
    'ranger':  ((222, 228, 176), (172, 182, 118), (118, 130, 78), (76, 86, 54), (54, 62, 40)),
}

# Per-class body (ground) tones for the recolor, visible on sleep frames only; taken off the flank
# and groove stops so the piece reads as one object.
BODY = {
    'warrior': ((46, 50, 64), (108, 116, 134), (170, 180, 198)),
    'mage':    ((32, 40, 84), (78, 104, 174), (132, 176, 226)),
    'ranger':  ((52, 60, 38), (116, 128, 76), (176, 186, 118)),
}

# One config block per slot. `largest` restricts the field to the biggest connected component
# (torso / dome) so raised arms are not covered; boots/legs pattern all opaque pixels.
SLOTS = {
    'chest': dict(
        outdir='_flowgrain_legendary_preview',
        srcs={'warrior': 'armor_chest_4', 'mage': 'shirt_mage4', 'ranger': 'shirt_ranger4'},
        dst='shirt_%s_legendary51', largest=True,
    ),
    'legs': dict(
        outdir='_flowgrain_legs_preview',
        srcs={'warrior': 'armor_pants_4', 'mage': 'pants_mage4', 'ranger': 'pants_ranger4'},
        dst='pants_%s_legendary51', largest=False,
    ),
    'boots': dict(
        outdir='_flowgrain_boots_preview',
        srcs={'warrior': 'armor_boots_4', 'mage': 'boots_mage4', 'ranger': 'boots_ranger4'},
        dst='boots_%s_legendary_flowgrain', largest=False,
    ),
    'helmet': dict(
        outdir='_flowgraindome_helmet_preview',
        srcs={'warrior': 'helmet_rare1', 'mage': 'helmet_mage4', 'ranger': 'helmet_ranger4'},
        dst='helmet_%s_legendary51', largest=True,
    ),
}


def phase_field(h, w, pitch=None):
    """PHI over an h x w box, in radians, one period per ridge.

    The carrier is a plane wave; each defect adds `q * w(r) * atan2(dy, dx)`, a half-turn of phase
    per circuit, which is a ridge ending (the delta) or a ridge closing on itself (the knot). The
    `w(r)` roll-off is what keeps ridge spacing finite at the cores — see the module docstring."""
    p = PITCH if pitch is None else pitch
    yy, xx = np.mgrid[0:h, 0:w].astype(np.float64)
    phi = (TAU / p) * (xx * np.cos(ALPHA) + yy * np.sin(ALPHA))
    for q, fx, fy in (KNOT, DELTA):
        dx, dy = fx * max(w - 1, 1), fy * max(h - 1, 1)
        ex, ey = xx - dx, yy - dy
        r2 = ex * ex + ey * ey
        phi = phi + q * (r2 / (r2 + CORE_R * CORE_R)) * np.arctan2(ey, ex)
    return phi


def paint_flowgrain(fr, comp, grain, pitch=None):
    """Paint the grain onto one component. Only opaque body pixels are ever painted, so this cannot
    create strays.

    Two things happen per pixel: the position within the ridge period picks the stop, and — for
    crest pixels only — the RIDGE'S LOCAL DIRECTION picks between the two crest stops. The light is
    upper-left throughout the set, so a ridge running across the light catches it and one running
    along it does not, and because the direction turns continuously the highlight travels along the
    grain instead of sitting in a fixed place."""
    if comp.sum() < MIN_PX:
        return
    ys, xs = np.nonzero(comp)
    y0, x0 = int(ys.min()), int(xs.min())
    h = int(ys.max()) - y0 + 1
    w = int(xs.max()) - x0 + 1
    phi = phase_field(h, w, pitch)
    t = np.mod(phi / TAU, 1.0)
    gy, gx = np.gradient(phi)
    # the ridge runs perpendicular to the gradient; how much it faces the upper-left light is
    # |sin| of the angle between the ridge and the light direction, i.e. the normalised component
    # of the gradient along the light.
    # light comes from the UPPER LEFT, and image y grows DOWNWARD, so the light direction is
    # (-1, -1)/sqrt(2) — not 135 degrees read off a maths-convention protractor, which points
    # down-left and highlights exactly the wrong family of ridges.
    gmag = np.hypot(gx, gy) + 1e-6
    lx_, ly_ = -0.70710678, -0.70710678
    face = np.abs((gx * lx_ + gy * ly_) / gmag)

    crest_hi, crest_lo, flank, groove, deep = grain
    left = np.zeros_like(comp)
    right = np.zeros_like(comp)
    up = np.zeros_like(comp)
    left[:, 1:] = comp[:, :-1]
    right[:, :-1] = comp[:, 1:]
    up[1:, :] = comp[:-1, :]
    thin_m = comp & ~(left & right)
    edge_m = comp & ~up

    for y, x in zip(ys, xs):
        ly, lx = int(y) - y0, int(x) - x0
        tv = t[ly, lx]
        if tv < T_CREST:
            # the standing edge rule: the brightest stop never lands on a silhouette edge or on a
            # 1px protrusion, or the piece grows a detached bright rim (the 47th / 49th lesson).
            if edge_m[y, x] or thin_m[y, x]:
                rgb = crest_lo
            else:
                rgb = crest_hi if face[ly, lx] > FACE_T else crest_lo
        elif tv < T_FLANK:
            rgb = flank
        elif tv < T_GROOVE:
            rgb = groove
        else:
            rgb = deep
        fr[y, x, :3] = rgb
        fr[y, x, 3] = 255


def label4(mask):
    """Self-contained 4-connectivity connected-component labelling (scipy-free).
    Returns (labels int32 array, n). Background (False) is label 0."""
    h, w = mask.shape
    labels = np.zeros((h, w), dtype=np.int32)
    n = 0
    stack = []
    for sy in range(h):
        for sx in range(w):
            if mask[sy, sx] and labels[sy, sx] == 0:
                n += 1
                labels[sy, sx] = n
                stack.append((sy, sx))
                while stack:
                    y, x = stack.pop()
                    if y > 0 and mask[y - 1, x] and labels[y - 1, x] == 0:
                        labels[y - 1, x] = n
                        stack.append((y - 1, x))
                    if y < h - 1 and mask[y + 1, x] and labels[y + 1, x] == 0:
                        labels[y + 1, x] = n
                        stack.append((y + 1, x))
                    if x > 0 and mask[y, x - 1] and labels[y, x - 1] == 0:
                        labels[y, x - 1] = n
                        stack.append((y, x - 1))
                    if x < w - 1 and mask[y, x + 1] and labels[y, x + 1] == 0:
                        labels[y, x + 1] = n
                        stack.append((y, x + 1))
    return labels, n


def load_any(fname):
    """Load a source sheet; if the female (_f) variant is absent (warrior boots are a
    single gender-shared sheet), fall back to the base sheet."""
    if os.path.exists(os.path.join(CHAR, fname)):
        return load(fname)
    if fname.endswith('_f.png'):
        return load(fname[:-6] + '.png')
    raise FileNotFoundError(fname)


def put(fr, y, x, rgb):
    if 0 <= y < FH and 0 <= x < FW:
        fr[y, x, :3] = rgb
        fr[y, x, 3] = 255


def recolor(src, fr, a, D, M, L):
    v = src[..., :3].astype(np.float32).max(-1) / 255.0
    vref = float(np.median(v[a]))
    ratio = v / max(vref, 1e-3)
    for y, x in np.argwhere(a):
        q = ratio[y, x]
        tone = D if q < Q_LO else (L if q > Q_HI else M)
        put(fr, y, x, tone)


def build(base, cfg, cls):
    D, M, L = BODY[cls]
    grain = GRAIN[cls]
    largest = cfg['largest']
    out = np.zeros_like(base)
    for fi in range(NFR):
        r, c = fi // COLS, fi % COLS
        sl = (slice(r * FH, (r + 1) * FH), slice(c * FW, (c + 1) * FW))
        src = base[sl]
        a = src[..., 3] > 0
        if not a.any():
            continue
        fr = out[sl]
        recolor(src, fr, a, D, M, L)
        if fi >= 60:                            # sleep: body only
            continue
        if largest:
            lbl, n = label4(a)
            if n >= 1:
                counts = np.bincount(lbl.ravel())
                counts[0] = 0
                comp = (lbl == int(counts.argmax()))
            else:
                comp = a
        else:
            comp = a
        paint_flowgrain(fr, comp, grain)
        # connectivity guard (no-op by construction: only body pixels repainted)
        da = fr[..., 3] > 0
        lbl2, _ = label4(da)
        keep_labels = set(np.unique(lbl2[a])) - {0}
        keep = np.isin(lbl2, list(keep_labels)) if keep_labels else da
        for y, x in np.argwhere(da & ~keep):
            fr[y, x, :] = 0
    return out


# --- diagnostics ----------------------------------------------------------------------------
def _test_plate(w=44, h=30):
    """A synthetic armour-ish plate: a rounded slab with a neck notch and a waist pinch, so the
    grain can be judged on a shape that has the features real slots have."""
    m = np.zeros((h, w), dtype=bool)
    yy, xx = np.mgrid[0:h, 0:w]
    cx = w / 2.0
    for y in range(h):
        ty = y / (h - 1.0)
        hw = 8.5 - 4.0 * abs(ty - 0.55) - 2.5 * max(0.0, 0.18 - ty) * 6.0
        hw = max(hw, 1.5)
        m[y, :] = np.abs(xx[y, :] - cx) <= hw
    m[0:3, int(cx) - 2:int(cx) + 3] = False          # neck notch
    return m


def swatch(path='_diag_flowgrain_swatch.png', zoom=12):
    """Render the bare motif on the test plate for all three classes, so the sweep of the grain, the
    knot and the delta can be judged before any sheet is written."""
    m = _test_plate()
    h, w = m.shape
    pad = 3
    tw, th = w * zoom, h * zoom
    img = Image.new('RGBA', (tw * 3 + pad * 4, th + pad * 2), (24, 24, 28, 255))
    for k, cls in enumerate(('warrior', 'mage', 'ranger')):
        a = np.zeros((h, w, 4), dtype=np.uint8)
        paint_flowgrain(a, m, GRAIN[cls])
        t = Image.fromarray(a).resize((tw, th), Image.NEAREST)
        img.paste(t, (pad + k * (tw + pad), pad))
    img.save(path)
    print('wrote %s (motif only - no sheets written)' % path)


def sweep(path='_diag_flowgrain_sweep.png', zoom=11):
    """Render the warrior chest idle frame at a range of ridge pitches, plus a leg frame, so the
    pitch can be judged on a real piece: at the coarse end on whether enough members survive for
    the flow to read as a flow, and at the fine end on whether the crest-flank-groove profile
    survives at all."""
    base = load_any('armor_chest_4.png')
    legs = load_any('armor_pants_4.png')
    cells = []
    for p in (5.5, 4.5, 4.0, 3.6, 3.0):
        col = []
        for arr, crop in ((base, (26, 20, 54, 46)), (legs, (26, 36, 54, 62))):
            src = arr[0:FH, 0:FW]
            a = src[..., 3] > 0
            lbl, n = label4(a)
            counts = np.bincount(lbl.ravel())
            counts[0] = 0
            comp = (lbl == int(counts.argmax())) if n else a
            fr = np.zeros_like(src)
            paint_flowgrain(fr, comp, GRAIN['warrior'], pitch=p)
            col.append(Image.fromarray(fr).crop(crop))
        cells.append(('PITCH=%.1f' % p, col))
    cw, ch = 28 * zoom, 26 * zoom
    pad, lab = 8, 18
    img = Image.new('RGBA', (pad + len(cells) * (cw + pad), pad * 2 + 2 * (ch + lab)), (24, 24, 28, 255))
    from PIL import ImageDraw, ImageFont
    d = ImageDraw.Draw(img)
    try:
        f = ImageFont.truetype('/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf', 13)
    except Exception:
        f = ImageFont.load_default()
    x = pad
    for name, col in cells:
        y = pad
        for im in col:
            img.alpha_composite(im.resize((cw, ch), Image.NEAREST), (x, y))
            d.text((x + 2, y + ch), name, font=f, fill=(210, 210, 220, 255))
            y += ch + lab
        x += cw + pad
    img.convert('RGB').save(path)
    print('wrote %s (pitch sweep - no sheets written)' % path)


def dump_field():
    """ASCII dump of the field on a torso-sized box plus the gradient statistics.

    The stats are the actual acceptance test for this axis. `p95 / median` of |grad PHI| is the
    worst-case ridge-spacing compression: at 1.0 the grain is perfectly even (and there is no
    field), and much above 2 the defect cores compress the spacing below a pixel and turn into the
    alternating mush that killed the 30th cable's first cut. CORE_R is set from this number."""
    for label, (hh, ww) in (('torso 13x20', (20, 13)), ('plate 30x44', (30, 44))):
        phi = phase_field(hh, ww)
        gy, gx = np.gradient(phi)
        g = np.hypot(gx, gy)
        t = np.mod(phi / TAU, 1.0)
        ch = np.where(t < T_CREST, '#', np.where(t < T_FLANK, '+', np.where(t < T_GROOVE, '-', '.')))
        print('== %s   PITCH=%.1f ALPHA=%.0fdeg CORE_R=%.1f' % (label, PITCH, np.rad2deg(ALPHA), CORE_R))
        print('   |grad| median=%.2f p95=%.2f  ratio=%.2f  (carrier=%.2f)'
              % (np.median(g), np.percentile(g, 95), np.percentile(g, 95) / np.median(g), TAU / PITCH))
        for y in range(hh):
            print('   ' + ''.join(ch[y]))
    # the two defects, as fractions and as pixels on a 13x20 torso
    for nm, (q, fx, fy) in (('KNOT ', KNOT), ('DELTA', DELTA)):
        print('%s charge=%+.1f periods per circuit  at (%.2f, %.2f) -> torso px (%.1f, %.1f)'
              % (nm, q, fx, fy, fx * 12, fy * 19))


def main():
    if '--field' in sys.argv:
        dump_field()
        return
    if '--swatch' in sys.argv:
        swatch()
        return
    if '--sweep' in sys.argv:
        sweep()
        return
    for kind, cfg in SLOTS.items():
        outdir = cfg['outdir']
        os.makedirs(outdir, exist_ok=True)
        for cls, srcstem in cfg['srcs'].items():
            for suffix in ('', '_f'):
                base = load_any('%s%s.png' % (srcstem, suffix))
                arr = build(base, cfg, cls)
                dst = '%s/%s%s.png' % (outdir, cfg['dst'] % cls, suffix)
                # MANDATORY finishing pass - never a bespoke shade() in a generator.
                # save_finished() rather than a bare .save(): it writes the TaskQuestFinish
                # version stamp, without which a later bulk `sprite_finish.py <dir>` backfill
                # would run the whole chain over these sheets a SECOND time.
                arr, info = finish_array(arr, dst)
                save_finished(arr, dst)
                print('wrote %-64s opaque_px=%-6d finish=%s/%s'
                      % (dst, (arr[..., 3] > 0).sum(), info['slot'], info['variant']))


if __name__ == '__main__':
    main()
